// Client
export const SAVE_JOBS = 'SAVE_JOBS';
export const SET_REASON = 'SET_REASON';
export const SET_STT_RESPONDED_DISPUTE = 'SET_STT_RESPONDED_DISPUTE';

// Rating
export const GET_RATING_LOGS = 'GET_RATING_LOGS';
export const GET_RATING_LOGS_SUCCESS = 'GET_RATING_LOGS_SUCCESS';
export const GET_RATING_LOGS_ERROR = 'GET_RATING_LOGS_ERROR';

// Common
export const SET_VIEW = 'SET_VIEW';
export const SET_ACTION_BTN_DISABLED = 'SET_ACTION_BTN_DISABLED';
export const SET_YOUR_NETWORK = 'SET_YOUR_NETWORK';
export const SET_RELOAD = 'SET_RELOAD';
export const SAVE_ACCOUNT_INFO = 'SAVE_ACCOUNT_INFO';
export const SET_REGISTER = 'SET_REGISTER';

// freenlacer
export const SAVE_VOTING_PARAMS = 'SAVE_VOTING_PARAMS';
export const SET_STT_DISPUTE_CREATED = 'SET_STT_DISPUTE_CREATED';

// home
export const LOGIN_METAMASK = 'LOGIN_METAMASK';
export const LOGOUT_METAMASK = 'LOGOUT_METAMASK';
export const SET_WEB3 = 'SET_WEB3';
export const SET_ACCOUNT = 'SET_ACCOUNT';
export const SET_NETWORK = 'SET_NETWORK';
export const SET_CHECK_ACCOUNT = 'SET_CHECK_ACCOUNT';

// dispute
export const SAVE_DISPUTES = 'SAVE_DISPUTES';
export const SAVE_VOTE = 'SAVE_VOTE';
export const SET_VOTE_INPUT_DISABLE = 'SAVE_VOTE_INPUT_DISABLE';
export const SAVE_REVEAL_VOTE = 'SAVE_REVEAL_VOTE';

// exchange
export const GET_EXCHANGE_RATES = 'GET_EXCHANGE_RATES';
export const GET_EXCHANGE_RATES_ERROR = 'GET_EXCHANGE_RATES_ERROR';
export const GET_EXCHANGE_RATES_SUCCESS = 'GET_EXCHANGE_RATES_SUCCESS';

// tokens
export const GET_TOKENS_ADDRESS = 'GET_TOKENS_ADDRESS';
export const GET_TOKENS_ADDRESS_SUCCESS = 'GET_TOKENS_ADDRESS_SUCCESS';
export const GET_TOKENS_ADDRESS_ERROR = 'GET_TOKENS_ADDRESS_ERROR';
export const SAVE_TOKENS = 'SAVE_TOKENS';
