image: 'docker:latest'
services:
    - 'docker:dind'
variables:
    DOCKER_HOST: 'tcp://localhost:2375'
    BUCKET_URL_dev: 'gs://dev-marketplace.bigbom.net'
    BUCKET_URL_uat: 'gs://uat-marketplace.bigbom.net'
    BUCKET_URL_production: 'gs://marketplace.bigbom.com'
stages:
    - test
    - deploy
test:
    stage: test
    script: 'docker run --rm -v ${PWD}:/home -w /home node:latest sh -c "yarn install && yarn test"'
    only:
        - '/^v([0-9.]+)(-RC[\d+])?$/'
        - master
before_script:
    - 'echo ${GOOGLE_KEY} > google-key.json'
    - 'echo ${GOOGLE_STORAGE} > google-storage.json'
deploy-dev:
    image: google/cloud-sdk
    stage: deploy
    script:
        - 'BUCKET_URL=${BUCKET_URL_dev}'
        - 'docker run --rm -v ${PWD}:/home -w /home node:latest sh -c "yarn install && yarn run build:${CI_ENVIRONMENT_NAME}"'
        - gcloud auth activate-service-account --key-file google-storage.json
        - 'gsutil -m -h "Cache-Control:public, max-age=604800" rsync -r -d ./build ${BUCKET_URL}'
    environment:
        name: dev
    only:
        - master
deploy-uat:
    image: google/cloud-sdk
    stage: deploy
    script:
        - 'BUCKET_URL=${BUCKET_URL_uat}'
        - 'docker run --rm -v ${PWD}:/home -w /home node:latest sh -c "yarn install && yarn run build:${CI_ENVIRONMENT_NAME}"'
        - gcloud auth activate-service-account --key-file google-storage.json
        - 'gsutil -m -h "Cache-Control:public, max-age=604800" rsync -r -d ./build ${BUCKET_URL}'
    environment:
        name: uat
    only:
        - '/^v([0-9.]+)-RC[\d+]$/'
deploy-production:
    image: google/cloud-sdk
    stage: deploy
    script:
        - 'BUCKET_URL=${BUCKET_URL_production}'
        - 'docker run --rm -v ${PWD}:/home -w /home node:latest sh -c "yarn install && yarn run build:${CI_ENVIRONMENT_NAME}"'
        - gcloud auth activate-service-account --key-file google-storage.json
        - 'gsutil -m -h "Cache-Control:public, max-age=604800" rsync -r -d ./build ${BUCKET_URL}'
    environment:
        name: production
    only:
        - '/^v([0-9.]+)$/'
