import { NAMESPACE_AAA } from '../../consts';

export const REQUEST_POSTS = `${NAMESPACE_AAA}/REQUEST_POSTS`;
export const RECEIVE_POSTS = `${NAMESPACE_AAA}/RECEIVE_POSTS`;
export const SELECT_REDDIT = `${NAMESPACE_AAA}/SELECT_REDDIT`;
export const INVALIDATE_REDDIT = `${NAMESPACE_AAA}/INVALIDATE_REDDIT`;
